//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrebovanjaNarudzbe.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokument
    {
        public int DokumentId { get; set; }
        public string Naziv { get; set; }
        public int NabavkaId { get; set; }
        public byte[] Dokument1 { get; set; }
    
        public virtual Nabavke Nabavke { get; set; }
    }
}
