//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrebovanjaNarudzbe.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nabavke
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nabavke()
        {
            this.Dokuments = new HashSet<Dokument>();
            this.NabavkaVeznas = new HashSet<NabavkaVezna>();
            this.Nabavke1 = new HashSet<Nabavke>();
        }
    
        public int NabavkaId { get; set; }
        public string SifraRadnika { get; set; }
        public string SifraReferentaNabavke { get; set; }
        public int TipId { get; set; }
        public int StatusNabavkeId { get; set; }
        public string SerijskiBroj { get; set; }
        public System.DateTime DatumPodnosenjaZahtjeva { get; set; }
        public Nullable<System.DateTime> DatumRazmatranjaZahtjeva { get; set; }
        public Nullable<System.DateTime> DatumPreuzimanja { get; set; }
        public Nullable<int> BrojDokumenata { get; set; }
        public string Obrazlozenja { get; set; }
        public string NapomenaSefa { get; set; }
        public string NapomenaReferentaNabavke { get; set; }
        public Nullable<int> VezanaNabavkaId { get; set; }
        public string Odgovoran { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokument> Dokuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NabavkaVezna> NabavkaVeznas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nabavke> Nabavke1 { get; set; }
        public virtual Nabavke Nabavke2 { get; set; }
        public virtual TipNabavke TipNabavke { get; set; }
        public virtual vRadnik vRadnik { get; set; }
        public virtual vRadnik vRadnik1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual DatumiOdobravanjaNabavke DatumiOdobravanjaNabavke { get; set; }
    }
}
