//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrebovanjaNarudzbe.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferentNabavke
    {
        public int ReferentId { get; set; }
        public int TipNabavkeId { get; set; }
        public string SifraRadnika { get; set; }
        public string Napomena { get; set; }
    
        public virtual TipNabavke TipNabavke { get; set; }
        public virtual vRadnik vRadnik { get; set; }
    }
}
