//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrebovanjaNarudzbe.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trebovanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trebovanje()
        {
            this.TrebovanjeVeznas = new HashSet<TrebovanjeVezna>();
        }
    
        public int TrebovanjeId { get; set; }
        public string SifraRadnika { get; set; }
        public string SerijskiBroj { get; set; }
        public System.DateTime DatumPodnosenjaZahtjeva { get; set; }
        public Nullable<System.DateTime> DatumZaduzenjaTrebovanja { get; set; }
        public string NapomenaRadnika { get; set; }
        public string NapomenaNadredjenog { get; set; }
        public int StatusTrebovanjaId { get; set; }
    
        public virtual DatumiOdobravanjaTrebovanje DatumiOdobravanjaTrebovanje { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrebovanjeVezna> TrebovanjeVeznas { get; set; }
        public virtual vRadnik vRadniks { get; set; }
    }
}
