//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrebovanjaNarudzbe.Models.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrebovanjeNabavkeContext : DbContext
    {
        public TrebovanjeNabavkeContext()
            : base("name=TrebovanjeNabavkeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DatumiOdobravanjaNabavke> DatumiOdobravanjaNabavkes { get; set; }
        public virtual DbSet<DatumiOdobravanjaTrebovanje> DatumiOdobravanjaTrebovanjes { get; set; }
        public virtual DbSet<Dokument> Dokuments { get; set; }
        public virtual DbSet<NabavkaVezna> NabavkaVeznas { get; set; }
        public virtual DbSet<Nabavke> Nabavkes { get; set; }
        public virtual DbSet<ReferentNabavke> ReferentNabavkes { get; set; }
        public virtual DbSet<RezervisaniArtikli> RezervisaniArtiklis { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TipNabavke> TipNabavkes { get; set; }
        public virtual DbSet<Trebovanje> Trebovanjes { get; set; }
        public virtual DbSet<TrebovanjeVezna> TrebovanjeVeznas { get; set; }
        public virtual DbSet<vInformacijeOArtiklu> vInformacijeOArtiklus { get; set; }
        public virtual DbSet<vRadnik> vRadniks { get; set; }
    }
}
