//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrebovanjaNarudzbe.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRadnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vRadnik()
        {
            this.Trebovanje = new HashSet<Trebovanje>();
            this.NabavkeRadnika = new HashSet<Nabavke>();
            this.NabavkeReferent = new HashSet<Nabavke>();
            this.ReferentNabavkes = new HashSet<ReferentNabavke>();
        }
    
        public string RadnikSifra { get; set; }
        public string Prezime { get; set; }
        public string Ime { get; set; }
        public string KorisnickoIme { get; set; }
        public string Email { get; set; }
        public string Nivo1OdobravanjaSifra { get; set; }
        public string Nivo2OdobravanjaSifra { get; set; }
        public string Nivo3OdobravanjaSifra { get; set; }
        public string SektorSifra { get; set; }
        public Nullable<byte> RadnikUlogaId { get; set; }
        public Nullable<int> TimId { get; set; }
        public string NazivTima { get; set; }
        public string SifraLideraTima { get; set; }
        public string NazivUloge { get; set; }
        public string NazivSektora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trebovanje> Trebovanje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nabavke> NabavkeRadnika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nabavke> NabavkeReferent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferentNabavke> ReferentNabavkes { get; set; }
    }
}
